dist: xenial
sudo: true
language: python
env:
  global:
    - COVERALLS_PARALLEL=true

install:
  - pip install tox
  - pip install coveralls

script:
  - tox -e $TOX_ENV -- --hypothesis-profile=ci --duration=20
  - if [[ $TOX_ENV == py* ]]; then coveralls; fi  # Upload coverage results from py* environments.

jobs:
  include:
    - stage: test
      python: "3.6"
      env: TOX_ENV="docs"
    - python: "2.7"
      env: TOX_ENV="lint2"
    - python: "3.6"
      env: TOX_ENV="lint3"
    - python: "2.7"
      env: TOX_ENV="py27"
    - python: "3.5"
      env: TOX_ENV="py35"
    - python: "3.6"
      env: TOX_ENV="py36"
    - python: "3.7"
      env: TOX_ENV="py37"

    - stage: deploy
      install: skip
      script: skip
      deploy:
        provider: pypi
        user: mark_bell
        password:
          secure: "DO7MPlu5wHJRjpWYpExA+q5XXbREHx+mwOaSeKfHMMdzx6mCzgkjbHjB7m1QzcZ2pe6UsO4MxARpSDB/SWYL3iTZFeki6fIBNBHYGp5V+J5DAkQ9ZtyXTiQPfg3bjG15jKTjm9LkKFoShiHCppbVXHVs8AOHbxmsN25rz19+B9t5hHg56pBUkYsMy5BJO1EJAw5H/NunxcS1Q19g72lMMELJ5tXBLjO6wqx9pMGVms6XUnl5Qteztv+YVVKU+i4oLQqLOZaB9/IO3KoMZBVLsx3Y8hf5Q40eCbivhcg0bmwu0mHgrQe3NRnf/f+MwhdNUPgtpCE1WPQAU6TzCQS8/vQJdfGamQJBzIfdDSeStPaz0hqQAas536nLa96AEe+UNlsezGPIRf7B/fBV2fithTilhKNUpLK5AE5Rn9KCVG0zCCmNK8gWmhM41vjZ/ZCtWPAa5B0ODtObvJzAXqCGxKjFIFyfleAYPX7CcPGUBXgI5i83KTWNsA8DFP2fshzS+6Nqw6+6ypWJEagTsPWfca2/7guAN6DGbdZtX8pV7r6OUgEYB4nxgvKjfq4eY/HkCdYCvVNlU95Ybbpu5fsGIF2D3/Oub1949XGcJ6sK86yuQcGNjm75ap05cldLUQir1pa3HrPiGgGDvvZnEKyVR72R1+bM06amOKSQxch7MXc="
        on:
          tags: true

