branches:
  only:
  - master
  - dev
  - /^v[0-9]+\.[0-9]+\.[0-9]+$/
language: python
python:
- 2.7
- 3.4
- 3.5
- 3.6
install:
- pip install -r requirements-dev.txt
- pip install --editable .
- pip install tox-travis
- pip install coveralls
script:
- flake8
- pylint flipper.kernel
- tox -- --hypothesis-profile=ci --duration=20
after_success:
- if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then coveralls; fi
deploy:
  provider: pypi
  user: mark_bell
  password:
    secure: 
  on:
    tags: true
    python: 2.7
