
trigger:
  branches:
    include:
    - '*'
  tags:
    include:
    - 'v*'

jobs:
- job: 'Test'
  pool:
    vmImage: 'Ubuntu-16.04'
  strategy:
    matrix:
      Lint:
        python.version: '3.8'
        TOXENV: 'lint'
      Python36:
        python.version: '3.6'
        TOXENV: 'py36'
      Python37:
        python.version: '3.7'
        TOXENV: 'py37'
      Python38:
        python.version: '3.8'
        TOXENV: 'py38'
  
  steps:
  - task: UsePythonVersion@0
    displayName: 'Use Python $(python.version)'
    inputs:
      versionSpec: '$(python.version)'
  - script: pip install tox
    displayName: 'Install tox'
  - script: tox -- --hypothesis-profile=ci --durations=20 --junitxml=results.xml
    displayName: 'Run tox'
  - task: PublishTestResults@2
    displayName: 'Publish results file'
    condition: startswith(variables['TOX_ENV'], 'py')
    inputs:
      testResultsFiles: 'results.xml'
      testRunTitle: 'Test results for Python $(python.version)'

