name: Build

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        tox: [lint, py37, py38, py39, py310, py311]
        include:
        - tox: lint
          python-version: "3.10"
        - tox: py37
          python-version: "3.7"
        - tox: py38
          python-version: "3.8"
        - tox: py39
          python-version: "3.9"
        - tox: py310
          python-version: "3.10"
        - tox: py311
          python-version: "3.11"
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout branch
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Display Python version
      run: |
        python -c "import sys; print(sys.version)"
        pip --version
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install tox
    - name: Run Tox
      run: |
        tox -- --hypothesis-profile=ci --durations=20
      env:
        TOXENV: ${{ matrix.tox }}

  release:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout branch
      uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Display Python version
      run: |
        python -c "import sys; print(sys.version)"
        pip --version
    - name: Build
      run: |
        python setup.py sdist
    - name: Publish
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.pypi }}
